Description: Bucket S3

Resources:

  BucketHoupaPedidosS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-pedidos-b2c-b2b
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
   

  Bucket2HoupaPedidosS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-pedidos-b2c-test